name: geoflutterfire_plus
description: geoflutterfire_plus enables your flutter app to store and query cloud firestore documents based on their geographic location.
version: 0.0.29
homepage: https://github.com/KosukeSaigusa/geoflutterfire_plus

environment:
    sdk: ">=2.17.0 <4.0.0"
    flutter: ">=2.10.0"

dependencies:
    cloud_firestore: ^5.2.1
    flutter:
        sdk: flutter
    rxdart: ^0.28.0

    dart_firebase_admin:
        git:
            url: https://github.com/binemmanuel/dart_firebase_admin.git
            ref: main
            path: packages/dart_firebase_admin

dev_dependencies:
    build_runner: ^2.4.11
    cloud_firestore_platform_interface: ">=6.3.1"
